/* ============================================================
   WordBubbles — 80 original passages, 20 per difficulty.
   Every text and title here was written for this game:
   no external source, no copyrighted material.
   Rule: passages contain NO apostrophes (the tokeniser splits on
   them). Proper nouns may appear; the engine never blanks them.
   ============================================================ */

/* rows are [title, text] */
const mkPool = (prefix, rows) => rows.map((r, i) => ({
  id: prefix + String(i + 1).padStart(2, '0'),
  title: r[0],
  text: r[1]
}));

/* ---------------- PRIMARY (very easy, short) ---------------- */
const POOL_PRIMARY = mkPool('pri', [
  ['My Cat', 'I have a cat. Her name is Lily. She is white and black. She likes to sleep on my bed. Every morning she wakes me up. I give her milk and fish. She plays with a small ball. When I come home, she runs to me. We are good friends. I love my cat very much.'],
  ['The Red Ball', 'Tom has a red ball. He plays with it in the park. One day the ball goes into a tree. Tom is sad. A tall man helps him. He gets the ball down. Tom says thank you. They play together. Tom is happy again. It is a good day.'],
  ['Rain', 'It is raining today. I look out of the window. The sky is gray. Water falls on the road. I take my blue umbrella. I put on my boots. I jump in the water. My sister laughs at me. We go home. Mom makes hot soup. It is warm and good.'],
  ['My School', 'My school is big. It has many rooms. My class is on the first floor. We have a nice teacher. She reads books to us. We write and draw. At break we play outside. I like my school. My best friend is in my class. We walk home together.'],
  ['A Big Dog', 'A big dog lives near my house. He is brown and very friendly. He likes to run and play. His name is Max. Every day I give him water. He wags his tail. One day he brings me a stick. We play in the garden. Max is a good friend to me.'],
  ['The Sun', 'The sun is very hot today. I put on my hat. My mother gives me cold water. We sit under a big tree. The birds sing in the tree. I see a small cat there. It sleeps in the shade. The sun goes down. The air is cool. We go home for dinner.'],
  ['My Bike', 'I have a new bike. It is red and small. My father teaches me to ride. At first I fall down. I am sad. He says, do not give up. I try again and again. Now I can ride fast. I ride to the park every day. I love my bike.'],
  ['Breakfast', 'Every morning I eat breakfast. I have bread and an egg. I drink warm milk. My mother makes it for me. My father drinks tea. My sister eats fruit. We sit at one table. We talk about our day. Then I go to school. Breakfast makes me strong.'],
  ['The Little Bird', 'A little bird sits on my window. It is brown and small. It sings a happy song. I give it some bread. It eats and flies away. Next day it comes again. It brings a friend. Now two birds sit there. They sing for me every morning. I like them very much.'],
  ['My Family', 'I live with my family. My father is tall. My mother is kind. I have one sister. She is little. We live in a small house. We have a garden. My mother grows flowers. My father likes to cook. In the evening we watch TV. I love my family.'],
  ['Snow', 'It is very cold. Snow falls all day. The ground is white. My sister and I go out. We make a snowman. We give him a hat and a scarf. Our dog runs in the snow. He is very happy. We go inside. Mom gives us hot milk. Winter is fun.'],
  ['The Bus', 'I take the bus to school. It is yellow. The driver is kind. He says good morning. I sit near the window. I see cars and trees. My friend sits with me. We talk and laugh. The bus stops at my school. I say thank you and get off.'],
  ['My Birthday', 'Today is my birthday. I am nine years old. My mother makes a big cake. My friends come to my house. We play games in the yard. I get many gifts. My best gift is a book. We eat cake and ice cream. Then we sing songs. I am very happy.'],
  ['The Park', 'There is a park near my house. It is big and green. Many children play there. Some run and some jump. I like to play on the swing. My brother likes the slide. We see ducks in the pond. Old people walk on the path. We go to the park on Sunday. We have a good time.'],
  ['My Shoes', 'I have new shoes. They are blue and white. My mother buys them for me. I wear them to school. They are very soft. I can run fast in them. I clean them every day. My friend says they look nice. I am happy. I love my new shoes.'],
  ['The Fish', 'I have a small fish. It lives in a bowl. It is orange and red. It swims all day long. I give it food in the morning. I watch it after school. It has a small friend. They swim together. I like to look at them. Fish are quiet pets.'],
  ['Morning', 'The sun comes up. The birds sing. I open my eyes. It is a new day. I wash my face. I eat my food. I put on my clothes. My bag is ready. I say goodbye to my mom. Then I walk to school. I am ready for the day.'],
  ['The Farm', 'My uncle has a farm. It is near a hill. He has cows and hens. The cows give milk. The hens give eggs. I like the little chicks. They are yellow and soft. I help my uncle feed them. We work in the sun. At night we sleep early. The farm is a nice place.'],
  ['My Teacher', 'My teacher is very kind. Her name is Miss Lee. She teaches us English. She tells us funny stories. She helps us when we are sad. She likes to sing with us. We draw pictures for her. She says we are good students. We like her a lot. She is the best.'],
  ['Water', 'I drink water every day. Water is good for us. I drink it in the morning. I drink it after sports. My mother says we need water. Plants need water too. My father gives water to the flowers. The dog drinks water from a bowl. Water helps us live. I like cold water best.']
]);

/* ---------------- EASY (lower junior high) ---------------- */
const POOL_EASY = mkPool('eas', [
  ['My Weekend', 'On Saturday I do not go to school. I get up late and eat a big breakfast. In the morning I help my mother clean the house. After lunch I ride my bike to the park. I meet my friends there. We play football and run around. In the evening I read a book at home. On Sunday we visit my grandparents. My grandmother cooks a wonderful dinner. I go to bed early because Monday is a school day.'],
  ['The New Puppy', 'Last week my family got a new puppy. He is small and brown with big black eyes. We call him Lucky. At first he was afraid of everything. He hid under the sofa and would not come out. After two days he began to play with us. He likes to run in the garden and chase his ball. My little brother takes care of him every day. Lucky is now the happiest dog in our house.'],
  ['A Trip to the Sea', 'Last summer my parents took me to the sea. We drove for three hours and arrived in the afternoon. The water was blue and warm. I swam with my father and made a big sand castle with my sister. My mother took many photos. We ate ice cream and watched the boats. When the sun went down, the sky turned orange and pink. It was a beautiful day that I will always remember.'],
  ['The School Library', 'Our school has a small library. It is quiet and full of books. There are stories about animals, space, and far away places. A kind woman works there. She helps us find books we like. We can take two books home for a week. I go there every Tuesday after class. I like to sit by the window and read. Books can take you anywhere in the world.'],
  ['A Cold Morning', 'When I woke up this morning, the window was white with snow. Everything outside was quiet. The trees looked like they were wearing white clothes. I put on my warm coat, a hat, and gloves. My father made hot chocolate for us. We drank it in the kitchen and watched the snow fall. After breakfast I played in the snow with my dog. It was a lovely winter morning.'],
  ['My Grandfather', 'My grandfather lives with us. He is old but very strong. Every morning he walks in the garden and waters the plants. He tells me stories about his childhood. He says that life was hard but simple in those years. He teaches me how to grow vegetables. He can fix almost anything with his hands. In the evening we play chess together. I learn a lot from him.'],
  ['The Lost Cat', 'My friend had a white cat named Snow. One day Snow went out and did not come back. My friend looked everywhere and was very sad. We put a note on the wall near the shop. Three days later, a woman called us. She found Snow in her garden. My friend ran there and held the cat. She was crying with joy. Snow is safe at home again.'],
  ['First Day of School', 'It was my first day at a new school. I felt nervous and did not know anyone. I walked into the classroom and sat alone. A girl next to me smiled and said hello. Her name was Anna. She showed me where to find the books and the toilets. At lunch she shared her food with me. By the end of the day, I had a new friend. I was not afraid any more.'],
  ['The Rainy Day', 'It rained all day, so we could not go outside. My brother and I stayed at home. We played cards and built a house with boxes. My mother made soup and bread for lunch. We watched the water run down the window. In the afternoon the rain stopped. A big rainbow appeared in the sky. We ran outside to see it. The air smelled clean and fresh.'],
  ['My Hobby', 'My hobby is drawing. I draw every day after school. I like to draw animals, trees, and people. My favourite thing to draw is my cat. I have many pencils in different colours. Sometimes my friend draws with me. We show our pictures to each other. My mother puts my best pictures on the wall. Drawing makes me feel calm and happy.'],
  ['The Market', 'Every Sunday my mother and I go to the market. It is busy and full of colours. Farmers sell fresh fruit and vegetables. There are sweet cakes and warm bread too. My mother buys what we need for the week. I help her carry the bags. Sometimes she buys me a small cake. The market is loud but happy. I like going there with her.'],
  ['The Kite', 'On a windy day my sister and I took our kite to the hill. It was red and yellow with a long tail. We ran and let the string go. Slowly the kite went up into the sky. It moved like a bird in the wind. My sister laughed and clapped her hands. Then the wind stopped. The kite came down slowly. We sat on the grass and drank our juice.'],
  ['A Good Friend', 'My best friend is called Ben. We are in the same class. He is tall and always smiles. He can run very fast and plays football well. When I have a problem, he always helps me. He shares his food and his books with me. We do our homework together. On weekends we ride our bikes in the park. A good friend is a great gift.'],
  ['My Room', 'My room is not big, but I like it. There is a bed, a desk, and a small chair. On the wall I have a map of the world. My books are on a shelf near the window. I keep my pencils in a cup. In the morning the sun comes in and makes the room bright. I do my homework here and read at night. It is my quiet place.'],
  ['The Old Man and the Birds', 'An old man lives near our house. Every morning he feeds the birds in the park. He brings bread and seeds in a small bag. The birds know him and fly to him. He talks to them quietly. When it is cold, he builds small houses for them. He says that animals need our help. I think he has a very kind heart.'],
  ['Learning to Cook', 'Last month my mother taught me to cook rice. First we wash the rice in water. Then we put it in a pot with salt. We wait for the water to boil. Then we turn the fire down and wait. It takes about twenty minutes. The rice smells very good. I made it for my family last Sunday. Everyone said it was delicious. I want to learn more dishes.'],
  ['The Snowman', 'After the snow stopped, my friends and I made a snowman. We used three big balls of snow. I found two stones for his eyes and a carrot for his nose. My friend gave him a red scarf. We put an old hat on his head. He looked funny and kind. We took a photo with him. That night it was warm, and the snowman slowly became small.'],
  ['A Visit to the Doctor', 'I did not feel well on Monday. My head hurt and my throat was sore. My mother took me to see a doctor. The doctor was friendly and asked me many questions. She looked at my throat and listened to my heart. She said I needed rest and warm drinks. I stayed in bed for two days. Now I feel much better. The doctor helped me a lot.'],
  ['The Little Garden', 'We have a small garden behind our house. In spring we plant seeds in the soil. We water them every morning. Soon green leaves come out. In summer we have tomatoes and beans. My mother uses them to cook our dinner. I like to watch the plants grow. It teaches me that good things take time. Everyone helps in our garden.'],
  ['The Football Game', 'On Friday our class played a football game. We played against the class next door. Both teams were strong. In the first half nobody scored a goal. After the break I got the ball and ran fast. I kicked it into the net. Everyone shouted with joy. The other team tried hard but could not score. We won the game. We shook hands at the end.']
]);

/* ---------------- MEDIUM (junior high) ---------------- */
const POOL_MEDIUM = mkPool('med', [
  ['The Mountain Village', 'High in the mountains there is a small village. Only about fifty families live there. The air is clean and the water comes from the snow. In summer, visitors walk along the narrow paths and take photos of the old stone houses. In winter, the roads close and the village becomes very quiet. The people make cheese and bread at home. They know each other well and help when someone is in trouble. Life there is simple, but the people say they are happy.'],
  ['A Letter from Afar', 'My cousin moved to another country last year. She writes to me once a month and tells me about her new life. She says the city is very big and the streets are always busy. The food is different, and sometimes she misses our mother. She studies hard because she wants to be a doctor. In her free time she plays basketball with her new friends. I read her letters many times. I hope she comes home this summer.'],
  ['The Old Fisherman', 'Every morning an old fisherman goes out to sea. He has a small wooden boat and a simple net. He knows the water very well and can tell when a storm is coming. People in the town buy his fish at the market. He is over sixty but still works every day. He says the sea has given him everything he needs. When he returns, he sits by the harbour and tells stories to the children. They love to listen.'],
  ['The Brave Firefighter', 'A fire started in a tall building in the middle of the night. People ran out into the street. A firefighter named Peter ran inside to help. He climbed the stairs and opened the doors. He found an old woman and carried her down. The smoke was thick and it was hard to breathe. When he came out, everyone cheered. The newspaper wrote a story about him. Peter said he was only doing his job. He is a true hero.'],
  ['Learning a Language', 'Learning a new language is not easy, but it is interesting. At first the words sound strange and you cannot remember them. You must listen, read, and speak every day. One student says that watching films helps her a lot. Another student keeps a small notebook and writes new words in it. Mistakes are normal and nobody should be afraid of them. Slowly, the language begins to feel natural. Being able to talk to people from other countries is a wonderful feeling.'],
  ['The Chocolate Shop', 'On the corner of our street there is a small chocolate shop. The owner makes everything by hand. The smell from the shop is sweet and warm. Children stop there after school and look at the window. Inside there are boxes of dark chocolate, milk chocolate, and sweets with nuts and fruit. The prices are not cheap, but the quality is very good. On cold days the shop is full. The owner says he has done this work for thirty years and still loves it.'],
  ['A New Invention', 'A young engineer built a machine that turns rain into drinking water. She worked on it for three years in a small room. At first nothing worked, but she did not stop. She tried again and again until the machine finally worked. Now it is used in villages without clean water. The machine is cheap and easy to carry. Many people say her invention will help thousands of families. When asked about her success, she smiles and says the best ideas come from real problems.'],
  ['The Train Journey', 'Last winter I travelled by train to visit my grandparents. The journey took eight hours. I sat by the window and watched the towns, forests, and frozen rivers go by. A family sat next to me and shared their apples. We talked about our journeys and drank warm tea. When night came, the lights of houses looked like small stars. I did not sleep much because everything was so interesting. In the morning, my grandparents were waiting at the station.'],
  ['The Nervous Speaker', 'Sara had to give a talk in front of her whole class. She was so nervous that her hands were shaking. The night before, she practised many times in her room. She wrote her speech on small cards and read it aloud to her brother. On the day, her teacher smiled and said she could begin. Sara took a deep breath and started to speak. Her voice was quiet at first, but then it became strong. When she finished, everyone clapped. Now she is not afraid of talking any more.'],
  ['Clean Water Project', 'Students at our school started a project to save water. They put signs in every bathroom and fixed taps that were leaking. They also made posters about how to use less water at home. In one month, the school used twenty percent less water. The project was not expensive, and everyone could join. Some students visited younger classes and explained why water is important. The head teacher said the idea came from the students, and that made her proud. Small actions can make a big difference.'],
  ['The Mountain Climb', 'Last year my uncle took me to climb a small mountain near our town. We started early in the morning with water and a map. The path was steep, and my legs hurt after the first hour. My uncle told me to walk slowly and rest often. After three hours we reached the top. From there we could see the whole valley and the river below. The view was beautiful and the air was fresh. We ate our lunch and took photos. Going down was easier. I will never forget that day.'],
  ['The Old Clock', 'In our living room there is an old clock that has been in the family for a century. It belonged to my great grandmother. Every hour it rings with a clear soft sound. Last month it suddenly stopped. My father opened it carefully and cleaned the small parts. He found a broken spring and replaced it. When the clock began to tick again, my mother smiled. She said it sounded like the voice of an old friend. We hope it will work for another hundred years.'],
  ['A Day Without Screens', 'Last weekend our teacher asked us to spend one day without phones, computers, or televisions. At first I thought it would be boring. In the morning I read a book and helped my mother cook. In the afternoon I went to the park with my friend and we played for hours. We talked about many things and laughed a lot. In the evening I went to bed early. The next day I felt calm and rested. Maybe we should all try it again.'],
  ['The Busy Doctor', 'Doctor Chen works in a small hospital in a busy city. Every day she sees more than forty patients. Some have simple colds, and others are very ill. She listens carefully to everyone and never hurries them. When she has a free moment, she studies new medical books. She says medicine changes quickly and she must keep learning. At night she goes home late and tired, but she never complains. Many people say she is the kindest doctor in the hospital.'],
  ['The School Festival', 'Every spring our school holds a festival. Students prepare songs, plays, and games for weeks before. Teachers help us build a small stage in the yard. Parents come in the afternoon with food and drinks. The younger children sing, and the older ones put on a short play. There are games and small prizes for everyone. In the evening we sit together and watch the sky get dark. The festival is a lot of work, but it is the happiest day of the school year.'],
  ['The Helpful Neighbour', 'Our neighbour Mrs Patel is always ready to help. If someone is ill, she cooks soup and brings it to their door. If a child loses a ball, she finds it in her garden. When our family went away last summer, she watered our plants and looked after our cat. She never asks for anything in return. She says that neighbours should take care of each other. On her birthday, all the people in our street bring her small gifts. Kindness comes back in surprising ways.'],
  ['The Robot Helper', 'Scientists have built a robot that can help older people at home. It can carry small things, turn off lights, and remind people to take their medicine. It can also call a doctor if something is wrong. The robot speaks in a soft voice and is easy to use. Some people think robots are cold, but the old man who tested it says it keeps him company. He reads to it in the evening. Technology can be useful when it is designed with care.'],
  ['The Lost Wallet', 'On my way home I found a brown wallet lying on the ground. I opened it and saw a lot of money inside. There was also a photo of a family and an identity card. I did not take the money. I walked to the address on the card and knocked on the door. An old man opened it and looked very surprised. He had lost the wallet that morning. He thanked me many times and wanted to give me some money, but I said no. Being honest made me feel good.'],
  ['The Winter Market', 'Every December our town holds a winter market in the main square. Small wooden houses sell hot drinks, bread, and handmade gifts. Strings of warm lights hang between the trees. A band plays music, and children run between the houses. The air smells of chocolate and orange. People wear thick coats and warm hats. They meet friends and talk for hours. On the last night, there is a big fire and everyone sings together. It is the warmest time of the coldest month.'],
  ['A Good Teacher', 'Mr Ali has taught maths for twenty years. He is famous for his patience. When a student does not understand, he explains the problem again in a different way. He never says that a question is silly. He asks the class to solve hard problems together. He also tells his students that making mistakes is part of learning. Many of them were afraid of maths before, and now they enjoy it. Years later, students still come back to visit him. A good teacher never forgets his students.']
]);

/* ---------------- HARD (upper junior high) ---------------- */
const POOL_HARD = mkPool('har', [
  ['The Silent Library', 'The library stands at the end of a narrow street, its stone steps worn smooth by generations of readers. Inside, tall shelves reach toward a painted ceiling, and dust drifts through the bars of afternoon light. A librarian sorts returned books, sliding each one into its proper place without a sound. Students lean over long wooden tables, tracing maps and copying careful notes. Near the window an elderly man reads newspapers from distant countries. The clock above the door ticks slowly, marking the quiet hours. When evening comes, the lamps glow softly, and the heavy doors close for the night.'],
  ['The Last Lighthouse Keeper', 'For forty years Elias has kept the lighthouse on the rocky island. Every evening he climbs the spiral stairs and lights the great lamp. Ships far out at sea depend on that beam of light, and he knows it. He lives alone with an old dog and a radio that rarely works. In winter the storms are terrible, and waves crash against the walls. Once he saved a fishing boat by guiding it through thick fog. The sailors still tell that story in the harbour. Elias says the sea is his teacher, and he never grows tired of its voice.'],
  ['The Inventor of Small Things', 'In a crowded workshop above a bakery, an inventor builds strange and useful machines. Shelves hold gears, springs, copper wire, and jars of tiny screws. He sketches his ideas on scraps of paper and pins them to the wall. Some inventions work on the first attempt; most fail many times before they succeed. He never seems discouraged. He measures, adjusts, and tries again, humming quietly while he works. Neighbours bring him broken clocks and radios, and he repairs them for free. Late at night, while the bread below is baking, his latest device finally hums to life.'],
  ['The Migration', 'Every autumn, thousands of birds leave the northern forests and fly south. The journey is more than three thousand kilometres long. Some fly during the day and rest at night; others travel under the cover of darkness. They use the sun, the stars, and the shape of the land to find their way. Young birds follow the older ones, learning the route for the first time. Many do not survive the crossing. Those that arrive rest in warm wetlands before moving on. In spring they return north again, following the same invisible paths their parents used.'],
  ['The Deep Ocean', 'Most of our planet is covered by oceans, and much of that water is deep and dark. In the deepest parts, sunlight never reaches, and the water is almost freezing. Yet life exists even there. Strange fish carry their own light and move slowly through the blackness. Some creatures have huge eyes; others have none at all. Scientists use small submarines to study these hidden worlds. Every year they discover new species that no one has ever seen. The deep ocean remains one of the last great mysteries on Earth.'],
  ['The Painter and the Storm', 'Amelia had painted for thirty years, but she had never painted a storm. One afternoon the sky turned a strange green, and the wind began to rise. Instead of going inside, she set up her canvas by the window. The rain hit the glass and the trees bent low. She worked quickly, mixing dark colours and bright flashes of white. When the storm passed, she looked at the picture and was surprised. It was the best thing she had ever made. She said the storm had painted itself through her hands.'],
  ['The Forgotten Recipe', 'In the bottom of an old cupboard, my grandmother found a notebook that had belonged to her mother. The pages were yellow and the writing was faint. Inside were recipes that nobody in our family had cooked for fifty years. There was a cake with honey and nuts, and a soup made from simple vegetables. We chose one recipe and tried it together. The cake did not look perfect, but it tasted wonderful. While we ate, my grandmother told us stories about her childhood. Some things are worth saving, even when we forget them.'],
  ['The Long Distance Runner', 'Daniel trains six days a week, whatever the weather. He runs along the river before school and again in the evening. His coach says that talent is useful but habit is stronger. In his first race he finished almost last, and he wanted to give up. Instead he wrote down every mistake and worked on them one by one. Two years later he won the regional championship. After the race he thanked the runners who had beaten him. They had taught him more than any victory, he said.'],
  ['The Street Musicians', 'Three musicians arrived in the town with little more than a violin, a drum, and an old guitar. They played in the square each evening, and people stopped to listen on their way home. The youngest sang songs about distant cities; the others answered with quick rhythms and low chords. Coins fell into an open case, and children danced near the fountain. When the rain began, the crowd hurried away, but the musicians kept playing beneath a narrow roof. Later they packed their instruments and walked toward the next village, promising to return in spring.'],
  ['The Climate Question', 'Scientists have warned for decades that the Earth is getting warmer. The main cause is the burning of coal, oil, and gas, which releases gases into the air. The results are already visible: ice is melting, sea levels are rising, and some regions face longer droughts. Many governments have promised to reduce their emissions, but progress has been slow. Some cities are taking action on their own by improving public transport and planting trees. Young people around the world are demanding change. The problem is global, and experts say that cooperation is the only real solution.'],
  ['The Ancient Game', 'The game of chess is more than a thousand years old. It began in Asia and spread slowly along trade routes to Europe and beyond. Kings and farmers played it, and the rules changed many times before they became fixed. Today millions of people play online, and computers can beat the best human players. Yet chess is still popular, because it is more than a competition. It teaches patience, planning, and the ability to think ahead. A single careless move can lose a game, just as in life. That is why it has survived for so long.'],
  ['The Bee and the Flower', 'Bees and flowers depend on each other in a relationship that is millions of years old. The flower offers sweet nectar, and the bee carries pollen from plant to plant. Without the bees, many fruits and vegetables would disappear. Without the flowers, the bees would have nothing to eat. Scientists are worried because bee populations are falling in many countries. Pesticides, disease, and the loss of wild land are all to blame. Farmers are now planting flowers along the edges of their fields. Small changes like these can protect a partnership that nature took a very long time to build.'],
  ['The Voyage Home', 'After two years of working abroad, Maria finally bought a ticket home. The flight was long, and she could not sleep. She thought about her parents, her old friends, and the smells of her childhood kitchen. When the plane landed, her heart was beating fast. Her mother was waiting at the gate, older than she remembered. They held each other for a long moment without speaking. That evening the whole family gathered around one table. Maria said that she had travelled far, but nowhere had felt like this. Home is not a place, she realised, but the people who wait for you.'],
  ['The Strength of Habit', 'Habits are small actions that we repeat without thinking. They save energy because the brain does not have to decide every time. Some habits help us, such as reading before bed or walking every morning. Others harm us, such as checking a phone the moment we wake up. Scientists say that changing a habit is difficult because the old pattern stays in the brain. The best approach is to replace it rather than remove it. Start small, repeat often, and be patient. After a few months, the new action begins to feel automatic. In the end, our habits shape who we become.'],
  ['The Vanishing Forest', 'The rainforest is one of the richest places on Earth. A single hectare may contain more species of trees than an entire continent. Yet every year large areas are cut down for wood, farming, and roads. When the forest disappears, the animals that live there have nowhere to go. The soil also suffers, because without roots and shade it dries out and washes away. Some countries have created protected areas, and local communities are learning to use the forest without destroying it. The trees produce much of the oxygen we breathe. Protecting them is not only about animals; it is about all of us.'],
  ['The Kindness of Strangers', 'When my bicycle broke down in a village I did not know, I thought I would be stuck there for hours. An old mechanic saw me pushing it along the road and waved me over. He opened his small workshop and looked at the damage. It took him an hour, and he refused to take any money. Instead he made tea, and we talked about his children and my studies. When I finally left, he said that someone had once helped him in the same way. Kindness, he explained, is something you pass on rather than pay back.'],
  ['The Future of Work', 'The way we work is changing faster than ever before. Machines and computers now do many tasks that people once did by hand. Some jobs disappear, while new ones appear that nobody could have imagined twenty years ago. Experts say that the most important skills will be learning quickly and working well with others. A single skill is no longer enough for a whole career. People will need to study and change direction several times in their lives. This can be frightening, but it can also be an opportunity. Those who keep learning will always find a place.'],
  ['The Mountain of Waste', 'Every year the world produces billions of tonnes of waste. Much of it ends up in rivers, oceans, and huge rubbish mountains outside cities. Plastic is the worst problem, because it breaks into tiny pieces that never disappear. Fish and birds often mistake these pieces for food. Some countries have banned single use plastic bags, and others charge money for them. Recycling helps, but experts say that using less is far better than recycling more. Changing what we buy and how we live is difficult, yet it is the only way to face a problem that belongs to everyone.'],
  ['The Gift of Reading', 'Reading is one of the cheapest pleasures in the world. A book can take you to another country, another century, or another mind. It costs almost nothing, and it waits patiently until you return. Reading slowly is a skill that many people are losing, because screens reward speed rather than thought. Yet a good book asks us to stop, to imagine, and to feel what others feel. Studies suggest that people who read regularly understand other people better. They also sleep better and worry less. In a busy life, a quiet hour with a book is a rare and valuable gift.'],
  ['The Teacher Who Listened', 'When I was fourteen, I was sure that I was bad at mathematics. I avoided the subject and stopped asking questions. Then a new teacher arrived, and she did something unusual. Instead of explaining the answer, she asked me what I was thinking. She listened carefully without interrupting. Slowly, I began to explain my mistakes out loud, and often I found the answer myself. By the end of the year I was helping others. She never changed my ability, because it had been there all along. She simply changed what I believed about myself.']
]);

const PASSAGE_POOLS = {
  primary: POOL_PRIMARY,
  easy: POOL_EASY,
  medium: POOL_MEDIUM,
  hard: POOL_HARD
};

/* flat list — used by the Super Mind word pool */
const PASSAGES = [].concat(POOL_PRIMARY, POOL_EASY, POOL_MEDIUM, POOL_HARD);

/* Difficulty tuning.
   step   = roughly "one blank every N eligible words"
   minLen = shortest word that may be blanked
   mult   = score multiplier
   Primary keeps the SAME blank density as Easy (step 8).          */
const DIFFICULTY = {
  primary: {
    step: 7, minLen: 3, mult: 0.8, label: 'Primary',
    desc: 'Very short, simple texts — the gentlest way in.'
  },
  easy: {
    step: 8, minLen: 4, mult: 1, label: 'Easy',
    desc: 'A gentle start — a few everyday words to fill in.'
  },
  medium: {
    step: 5, minLen: 4, mult: 1.5, label: 'Medium',
    desc: 'A steady challenge — more words and more gaps.'
  },
  hard: {
    step: 3, minLen: 3, mult: 2, label: 'Hard',
    desc: 'Many gaps, but Super Mind is here to help.'
  }
};
